"use strict";
let setupWorkspaceId=null,discoveredRoots=[],setupStep=1,setupGeneration=0,discoverController=null,jobTimer=null;
async function shelfPost(url,value){const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","X-Morningpaper-Token":state.token,...(state.workspaceId?{"X-Workspace-Id":state.workspaceId}:{})},body:JSON.stringify(value)});const data=await response.json();if(!response.ok)throw new Error(data.error||"操作没有完成");return data;}
function currentWorkspace(){return state.bootstrap?.workspaces.find(row=>row.id===state.workspaceId);}
function workspaceUI(){
 const personal=["personal","all","saved"].includes(state.filter),workspaces=state.bootstrap?.workspaces||[];
 $("#personal-sidebar").hidden=!personal||!state.bootstrap;$("#workspace-selector").innerHTML=workspaces.length?workspaces.map(row=>`<option value="${escapeHTML(row.id)}">${escapeHTML(row.name)}</option>`).join(""):'<option value="">尚未建立个人方案</option>';
 $("#workspace-selector").value=state.workspaceId||"";$("#welcome-panel").hidden=!personal||Boolean(state.workspaceId)||!state.bootstrap;$("#workspace-panel").hidden=!personal||!state.workspaceId;
 const profile=currentWorkspace();if(profile){$("#workspace-title").textContent="我的个人推荐";$("#workspace-description").textContent=`${state.bootstrap.hosts[profile.host]?.label||profile.host} · 已检查 ${state.inventory?.skills.length||0} 个定义`;}
}
async function refreshBootstrap(){state.bootstrap=await getJSON("/api/bootstrap");state.token=state.bootstrap.token;workspaceUI();}
function setSetupStep(step){setupStep=step;$("#setup-step-one").hidden=step!==1;$("#setup-step-two").hidden=step!==2;$("#setup-back").hidden=step!==2;$("#setup-step-label").textContent=`可选个人推荐 · 第 ${step} 步 / 共 2 步`;$("#setup-title").textContent=step===1?"看看我已有的能力":"哪些新能力值得了解";$("#setup-save").textContent=step===1?"检查已有技能":"生成个人推荐";$("#setup-save").disabled=false;$("#setup-dialog").scrollTop=0;}
function closeSetup(){setupGeneration++;discoverController?.abort();$("#setup-dialog").close();$("#setup-message").textContent="";navigate("home");}
function providerUI(){const provider=$("#setup-provider").value;$("#model-settings").hidden=provider==="codex";$("#base-url-label").hidden=provider!=="compatible";const configured=state.bootstrap?.providers[provider]?.configured;$("#provider-status").textContent=provider==="deepseek"?configured?"可使用本机已有的 DeepSeek 配置。":"可填写自己的 DeepSeek Key；不影响公开资讯浏览。":"填写兼容接口地址和模型；本地模型可使用本机地址。";}
function showRoots(roots){discoveredRoots=roots;$("#root-options").innerHTML=roots.map((row,index)=>`<label class="root-option"><input type="checkbox" data-root-index="${index}" ${row.exists===false?"":"checked"}><span>${escapeHTML(row.label||"技能目录")}<small>${escapeHTML(row.path)}</small></span></label>`).join("");$("#root-options").append($("#empty-inventory-option").content.cloneNode(true));const count=roots.filter(row=>row.exists!==false).length;$("#detected-summary").textContent=count?`已自动发现 ${count} 个技能目录。确认后点击检查即可，详细路径可展开查看。`:"没有发现标准目录，可手动选择、导入清单，或直接返回资讯首页。";}
async function detectRoots(){
 discoverController?.abort();discoverController=new AbortController();const generation=setupGeneration;const controller=discoverController;$("#detect-roots").disabled=true;$("#detected-summary").textContent="正在自动发现标准技能目录…";
 try{const response=await fetch("/api/discover?host="+encodeURIComponent($("#setup-host").value)+"&project_directory="+encodeURIComponent($("#setup-project").value),{signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||"目录发现暂未完成");if(generation!==setupGeneration||controller!==discoverController)return;showRoots(data.roots);}
 catch(error){if(error.name!=="AbortError"&&generation===setupGeneration)$("#detected-summary").textContent=error.message;}finally{if(generation===setupGeneration)$("#detect-roots").disabled=false;}
}
async function openSetup(edit=false){
 if(!await ensurePrivate()){await navigate("personal");return;}
 setupGeneration++;const profile=edit?currentWorkspace():null;setupWorkspaceId=profile?.id||null;$("#setup-personal-daily").checked=profile?.automatic_recommendations===true;
 $("#setup-host").value=profile?.host||"codex";$("#setup-provider").value=profile?.provider.id||(state.bootstrap.providers.codex.configured?"codex":"deepseek");$("#setup-name").value=profile?.name||"";$("#setup-model").value=profile?.provider.model||"deepseek-flash";$("#setup-base-url").value=profile?.provider.base_url||"";$("#setup-api-key").value="";$("#setup-goals").value=profile?.goals||"";$("#setup-stack").value=profile?.stack||"";$("#setup-project").value=profile?.project_directory||"";$("#setup-custom-roots").value="";$("#setup-message").textContent="";$("#root-options").innerHTML="";$("#advanced-settings").open=false;$("#directory-details").open=false;discoveredRoots=[];providerUI();setSetupStep(edit&&state.inventory&&!state.board?.needs_scan?2:1);$("#setup-dialog").showModal();
 if(setupStep===2)$("#scan-result-summary").textContent=`已有 ${state.inventory.skills.length} 个定义的检查记录，可以直接调整目标。`;
 if(profile?.roots.length)showRoots(profile.roots);else await detectRoots();
}
function setupValue(){const roots=Array.from(document.querySelectorAll("#root-options input[data-root-index]:checked")).map(input=>discoveredRoots[Number(input.dataset.rootIndex)]).filter(Boolean).map(({path,scope,label})=>({path,scope,label}));for(const path of $("#setup-custom-roots").value.split(/\r?\n/).map(row=>row.trim()).filter(Boolean))roots.push({path,scope:"custom",label:"自选技能目录"});const provider={id:$("#setup-provider").value};if(provider.id!=="codex")provider.model=$("#setup-model").value;if(provider.id==="compatible")provider.base_url=$("#setup-base-url").value;return {name:$("#setup-name").value||`${$("#setup-host").selectedOptions[0].textContent} 的个人推荐`,host:$("#setup-host").value,provider,goals:$("#setup-goals").value||"了解实用的 AI Skills，补充或改进已有能力",stack:$("#setup-stack").value,project_directory:$("#setup-project").value,roots,session_api_key:$("#setup-api-key").value};}
async function saveProfile(){const value={...setupValue(),automatic_recommendations:$("#setup-personal-daily").checked};const profile=setupWorkspaceId?await shelfPost("/api/workspace/update",{...value,workspace_id:setupWorkspaceId}):await shelfPost("/api/workspaces",value);setupWorkspaceId=profile.id;state.workspaceId=profile.id;await shelfPost("/api/workspace/select",{workspace_id:profile.id});await refreshBootstrap();return profile;}
async function checkSkills(){const generation=setupGeneration;const value=setupValue(),empty=$("#setup-confirm-empty")?.checked===true;if(!value.roots.length&&!empty)throw new Error("可展开手动选择目录或导入清单；也可以点击稍后再说继续看资讯。");await saveProfile();if(generation!==setupGeneration)return;if(!value.roots.length&&empty){await shelfPost("/api/inventory/import",{workspace_id:state.workspaceId,inventory:{skills:[],confirmed_empty:true}});await loadWorkspace(state.workspaceId);$("#scan-result-summary").textContent="已确认从基础能力开始。填写一个目标，或先看通用增量。";setSetupStep(2);return;}const job=await shelfPost("/api/jobs",{workspace_id:state.workspaceId,action:"scan",limit:18});$("#setup-message").textContent="正在检查定义，暂不调用推荐模型…";watchJob(job.id,state.workspaceId,true,generation);}
async function beginJob(action){if(!state.workspaceId){await openSetup();return;}if(action==="recommend"&&state.board?.needs_scan){await openSetup(true);return;}try{const job=await shelfPost("/api/jobs",{workspace_id:state.workspaceId,action,limit:18});$("#job-status").textContent=action==="scan"?"正在检查现有能力…":"正在生成可选的个人推荐…";watchJob(job.id,state.workspaceId);}catch(error){toast(error.message);$("#job-status").textContent=error.message;}}
function watchJob(jobId,workspaceId,inSetup=false,generation=setupGeneration){clearTimeout(jobTimer);const poll=async()=>{try{if(state.workspaceId!==workspaceId)return;const jobs=await getJSON("/api/jobs"),job=jobs.find(row=>row.id===jobId);if(!job)return;const target=inSetup?$("#setup-message"):$("#job-status");target.textContent=job.message;if(job.status==="running"){jobTimer=setTimeout(poll,1000);return;}$("#setup-save").disabled=false;await loadWorkspace(workspaceId);workspaceUI();if(job.status==="complete"&&inSetup&&generation===setupGeneration&&$("#setup-dialog").open){$("#scan-result-summary").textContent=`已读取 ${state.inventory?.skills.length||0} 个技能定义。账号和运行依赖仍需确认。`;$("#setup-message").textContent="";setSetupStep(2);}else if(job.status==="complete"){$("#job-status").textContent="已完成，结果保存在个人推荐中。";}else{target.textContent=job.message;if(job.message.includes("API Key"))$("#advanced-settings").open=true;}}catch{ $("#setup-message").textContent="连接暂时中断，仍可关闭并继续浏览资讯。";$("#setup-save").disabled=false;}};poll();}
$("#workspace-new").addEventListener("click",()=>openSetup());$("#welcome-start").addEventListener("click",()=>openSetup());$("#workspace-settings").addEventListener("click",()=>openSetup(true));$("#setup-close").addEventListener("click",closeSetup);$("#setup-later").addEventListener("click",closeSetup);$("#setup-back").addEventListener("click",()=>setSetupStep(1));$("#setup-dialog").addEventListener("cancel",event=>{event.preventDefault();closeSetup();});$("#setup-dialog").addEventListener("click",event=>{const rect=event.currentTarget.getBoundingClientRect();if(event.target===event.currentTarget&&(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom))closeSetup();});
$("#detect-roots").addEventListener("click",detectRoots);$("#scan-again").addEventListener("click",()=>openSetup(true));$("#generate-recommendations").addEventListener("click",()=>beginJob("recommend"));
$("#setup-provider").addEventListener("change",()=>{if($("#setup-provider").value==="deepseek")$("#setup-model").value="deepseek-flash";providerUI();});$("#setup-host").addEventListener("change",()=>{if(!setupWorkspaceId&&$("#setup-host").value==="deepcode"){$("#setup-provider").value="deepseek";$("#setup-model").value="deepseek-flash";providerUI();}detectRoots();});
$("#setup-form").addEventListener("submit",async event=>{event.preventDefault();$("#setup-save").disabled=true;try{if(setupStep===1)await checkSkills();else{const generation=setupGeneration;await saveProfile();if(generation!==setupGeneration||!$("#setup-dialog").open)return;$("#setup-dialog").close();state.filter="personal";await loadWorkspace(state.workspaceId);if(generation!==setupGeneration)return;await beginJob("recommend");}}catch(error){$("#setup-message").textContent=error.message;$("#setup-save").disabled=false;if(error.message.includes("模型")||error.message.includes("接口"))$("#advanced-settings").open=true;}});
$("#inventory-file").addEventListener("change",async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>1500000)throw new Error("清单过大，请保留名称与功能说明。");const inventory=JSON.parse(await file.text());await saveProfile();await shelfPost("/api/inventory/import",{workspace_id:state.workspaceId,inventory});await loadWorkspace(state.workspaceId);$("#scan-result-summary").textContent=`已导入 ${state.inventory.skills.length} 个定义，可继续或稍后再用。`;setSetupStep(2);}catch(error){$("#setup-message").textContent=error.message;}finally{event.target.value="";}});
$("#workspace-selector").addEventListener("change",async event=>{try{state.workspaceId=event.target.value;await shelfPost("/api/workspace/select",{workspace_id:state.workspaceId});await loadWorkspace(state.workspaceId);workspaceUI();}catch(error){toast(error.message);}});
document.addEventListener("skill-shelf-bootstrap",workspaceUI);document.addEventListener("skill-shelf-workspace",workspaceUI);document.addEventListener("skill-shelf-view",workspaceUI);
